#!/usr/bin/perl

use strict;
use English qw/-no_match_vars/;
use CGI::Simple;

# Directory containing the SEPMAC.cnf.xml files
our $TFTPBOOT_DIRECTORY = '/var/lib/tftpboot';

# Basic-auth username and password credentials
our $CGI_USERNAME = 'cisco';
our $CGI_PASSWORD = 'cisco';

eval {
    my $cgi = CGI::Simple->new;

    # Fix silly capitization of UserID and Password
    foreach my $name (qw/UserID Password/) {
        $cgi->param (lc $name, $cgi->param ($name));
        $cgi->delete ($name);
    }

    print 'Status: 200 OK', "\r\n",
          'Content-Type: text/plain', "\r\n",
          "\r\n";

    # Check that the device exists and the username and password are correct
    if ($cgi->param ('devicename') =~ m/^SEP[0-9A-F]{12}$/
        && stat ($TFTPBOOT_DIRECTORY . '/' . $cgi->param ('devicename') . '.cnf.xml')
        && $cgi->param ('userid') eq $CGI_USERNAME && $cgi->param ('password') eq $CGI_PASSWORD) {
        print 'AUTHORIZED';
    } else {
        print 'UNAUTHORIZED';
    }    
};

warn $EVAL_ERROR if (length $EVAL_ERROR);
