# This file contains the config needed for the phone XML services
# you can override the defalt location by setting the environment
# variable SERVIES_CONFIG.

# Where to write logs from the problem report tool.
#
# reports-dir: /var/log/cisco

# Basic authentication for when a request is sent to the phones
# CGI/Execute url.
#
# cgi-username: cisco
# cgi-password: cisco

# URL and credentials for the Asterisk web-server and manager
# interface.
#
# manager-url: http://localhost:8088/mxml
# manager-username: asterisk
# manager-secret: asterisk
